saveExact: true
engineStrict: true
minimumReleaseAge: 1440
minimumReleaseAgeExcludePrune: true
trustPolicy: "no-downgrade"
trustPolicyExclude:
  - semver@6.3.1||5.7.2
  - groq@3.88.1-typegen-experimental.0
allowBuilds:
  "@heroui/shared-utils": true
  "@parcel/watcher": true
  "@prisma/engines": true
  "@swc/core": true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.70'
  - '@ai-sdk/react@4.0.90'
  - '@next/env@16.3.4'
  - '@next/swc-darwin-arm64@16.3.4'
  - '@next/swc-darwin-x64@16.3.4'
  - '@next/swc-linux-arm64-gnu@16.3.4'
  - '@next/swc-linux-arm64-musl@16.3.4'
  - '@next/swc-linux-x64-gnu@16.3.4'
  - '@next/swc-linux-x64-musl@16.3.4'
  - '@next/swc-win32-arm64-msvc@16.3.4'
  - '@next/swc-win32-x64-msvc@16.3.4'
  - ai@7.0.87
  - next@16.3.4
  - '@eloqnt/config@0.1.0'
  - '@eloqnt/format-json@0.1.0'
  - '@eloqnt/format-po@0.1.0'
  - '@next/third-parties@16.3.4'
  - icu-minify@4.14.2
  - next-intl-swc-plugin-extractor@4.14.2
  - next-intl@4.14.2
  - use-intl@4.14.2
